# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 14:42
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 14, 42, 30, 985529), verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='car',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Ano'),
        ),
    ]
