# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171228_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 15, 13, 15, 91324), verbose_name='Data de Cadastro'),
        ),
    ]
