# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appN1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appN1.Brand'),
            preserve_default=False,
        ),
    ]
